[package]
name = "connectbox-shell"
version = "0.1.0"
edition = "2021"

[dependencies]
rustyline = "11"
color-eyre = "0.6"
tokio = { version = "1.0", default-features = false, features = ["macros"] }
tracing-subscriber = "0.3"
